print("Give me your personal information so I can sell it to the Chinese government! I won't do anything bad, trust me >:D")
first_name = input("First name: ")
last_name = input("Last name: ")
grade = input("School grade (9-12): ")
id = input("Student ID: ")
login = input("Login: ")
average = input("Average: ")

print("Your information stored by the one and only Chinese CCP Government:")
print(f"Login: {login}")
print(f"ID: {id}")
print(f"Name: {last_name}, {first_name}")
print(f"Average: {average}%")
print(f"Grade: {grade}")
